"""The proof that Tests/test_document_self_declaration.py is not vacuous.

Both directions are failures and they fail oppositely: a declaration that
goes unread lets a machine rewrite a frozen record, and a declaration read
too eagerly silences a real claim nobody will hear about. Every mutant
below is one of the two.

The working tree is never modified.
"""
from __future__ import annotations

import pytest

from mutant_harness import assert_killed, run_tests_with_mutation

DOCS = "Tests/test_document_self_declaration.py"
_M = "ghost_buster/mechanical.py"

MUTANTS = [
    # (label, file, exact text to replace, replacement)
    # --- the declaration goes unread ---
    ("the document's own declaration is never consulted", _M,
     '    if head and _DECLARED_NOT_LIVE.search(head[:_HEAD]):\n'
     '        return "a document that declares itself not maintained by hand"\n',
     ""),
    ("a head that was supplied is treated as absent", _M,
     "    if head and _DECLARED_NOT_LIVE.search(head[:_HEAD]):",
     "    if False and _DECLARED_NOT_LIVE.search(head[:_HEAD]):"),
    ("generated markers are dropped from the pattern", _M,
     '    r"@generated"\n'
     '    r"|<!--\\s*generated"\n'
     '    r"|\\bauto-?generated\\b"\n'
     '    r"|\\bgenerated by\\b"\n'
     '    r"|\\bdo not edit\\b"\n',
     '    r"@nothing-at-all"\n'),
    ("frozen-record wording is dropped from the pattern", _M,
     '    r"|\\brecord of a moment\\b"\n'
     '    r"|\\bis not updated\\b|\\bno longer updated\\b"\n',
     ""),
    ("the pattern becomes case sensitive, so DO NOT EDIT is missed", _M,
     '    r"|\\barchived (?:document|record|copy)\\b",\n    re.I)',
     '    r"|\\barchived (?:document|record|copy)\\b")'),
    # --- the declaration is read too eagerly ---
    ("the whole document is searched, not its head", _M,
     "_DECLARED_NOT_LIVE.search(head[:_HEAD])",
     "_DECLARED_NOT_LIVE.search(head)"),
    ("the head grows until prose about other files counts", _M,
     "_HEAD = 400",
     "_HEAD = 100000"),
    # --- the order of the signals ---
    ("the self-declaration answers before the name does", _M,
     '    if filename.lower() not in WRITABLE_DOCUMENTS:\n'
     '        return "not a current-state document"\n',
     ""),
]


@pytest.mark.parametrize("label,rel,old,new", MUTANTS, ids=[m[0] for m in MUTANTS])
def test_mutant_is_killed(label, rel, old, new):
    assert_killed(label, DOCS, run_tests_with_mutation(DOCS, rel, old, new))


def test_the_suite_passes_unmutated():
    anchor = "_HEAD = 400"
    result = run_tests_with_mutation(DOCS, _M, anchor, anchor)
    assert result.returncode == 0, result.stdout[-1500:]
