"""A document that says what it is, in its own words.

THE DEFECT THIS FILE GUARDS AGAINST (v1.7.4)

Writability was decided from two things: the NAME (`readme.md` is a
current-state document, `STATUS_REPORT.md` is not) and the sentence beside
the claim. Neither can carry what a file says about itself.

Two worlds got through, both ordinary, both found by an adversarial
harness:

    a README opening `<!-- generated: do not edit by hand -->`
    a README opening "Recorded 2026-01-14. This document is a record of a
      moment and is not updated afterwards."

The first is what documentation tooling produces every day. The second is
what happens to a project nobody archived properly. Both had their claim
rewritten, and the second is instructive: the dated-sentence check reads
the 70 characters before the claim with no full stop in them, and that
declaration is a paragraph away with two full stops in between. It was
never going to see it.

WHY THE HEAD AND NOT THE WHOLE FILE

A file that says what it is says so at the top. Searching the whole
document would let a phrase deep inside a long README -- about some other
file, most likely -- silence a real claim. The bound is `_HEAD`.

THE COST OF THIS GUARD

Refusing too much. That is a real cost and it is measured: an evaluator
that cannot see over-caution cannot tell a safe tool from a blind one. The
boundary tests below are as important as the ones above them.
"""
from __future__ import annotations

import pytest

from ghost_buster.mechanical import _HEAD, why_not_writable

CLAIM = "The test suite has 12 tests, all passing."
REFUSAL = "a document that declares itself not maintained by hand"


def _ask(body: str, filename: str = "README.md"):
    """Ask the predicate about the claim inside `body`, the way a caller
    does: a window each side, plus the document itself for its head."""
    text = body
    at = text.index("12 tests")
    return why_not_writable(filename, text[max(0, at - 240):at],
                            text[at:at + 240], text)


def _document(*head_lines: str) -> str:
    return ("# Example\n\n" + "".join(line + "\n\n" for line in head_lines)
            + "## Tests\n\n" + CLAIM + "\n")


# ------------------------------------------------- the two that got through

def test_a_generated_readme_is_refused():
    assert _ask(_document("<!-- generated: do not edit by hand -->")) == REFUSAL


def test_a_readme_that_is_a_record_of_a_moment_is_refused():
    assert _ask(_document(
        "Recorded 2026-01-14. This document is a record of a moment and is "
        "not updated afterwards.")) == REFUSAL


def test_the_declaration_is_a_paragraph_away_and_still_seen():
    """The specific reason the dated-sentence check could not do this job:
    it reads the text immediately before the claim, with no full stop in
    it, and a document-level declaration is neither."""
    body = _document(
        "Recorded 2026-01-14. This document is a record of a moment.",
        "Some intervening prose that has nothing to do with dates.",
        "And a second paragraph, also unrelated.")
    assert _ask(body) == REFUSAL


@pytest.mark.parametrize("declaration", [
    "@generated",
    "<!-- generated by doctool -->",
    "This file is auto-generated.",
    "Generated by mkdocs; do not edit.",
    "DO NOT EDIT",
    "This page is no longer updated.",
    "This document is no longer maintained.",
    "A point-in-time snapshot of the project.",
    "An archived copy of the 1.2 documentation.",
])
def test_the_ways_a_document_says_it_is_not_live(declaration):
    assert _ask(_document(declaration)) == REFUSAL


# ------------------------------------------- the cost: refusing too much

def test_an_ordinary_readme_is_still_writable():
    """The control. This guard must not close the remedy it guards."""
    assert _ask(_document("A small project, kept small.")) is None


def test_a_readme_that_merely_mentions_generated_code_is_still_writable():
    """"We generate the client from the schema" is a sentence about the
    project, not a declaration about this document. The bound on where the
    declaration may appear is what keeps these apart."""
    body = ("# Example\n\n" + "A small project.\n\n" + "## Tests\n\n"
            + CLAIM + "\n\n## Notes\n\n"
            + "x" * _HEAD + "\nThe API client is auto-generated from the "
            "schema; do not edit it by hand.\n")
    assert _ask(body) is None


def test_the_declaration_must_be_near_the_top():
    """Past the bound it is prose about something else."""
    filler = "Paragraph of ordinary prose about the project. " * 12
    assert len(filler) > _HEAD
    body = ("# Example\n\n" + filler + "\n\nThis file is auto-generated.\n\n"
            "## Tests\n\n" + CLAIM + "\n")
    assert _ask(body) is None


def test_a_document_that_says_nothing_about_itself_is_unaffected():
    assert _ask(_document("Contributions welcome.", "See CONTRIBUTING.md.")) is None


# ------------------------------------------------------ the signal's place

def test_the_name_still_decides_first():
    """A file the name already refuses is refused for that reason, not
    this one. The order of the signals is part of what the message means."""
    assert _ask(_document("A small project."),
                filename="STATUS_REPORT.md") == "not a current-state document"


def test_without_a_head_the_predicate_behaves_as_it_always_did():
    """Callers that do not pass the document lose nothing they had. An
    absent head is not evidence of anything."""
    body = _document("<!-- generated: do not edit by hand -->")
    at = body.index("12 tests")
    assert why_not_writable("README.md", body[max(0, at - 240):at],
                            body[at:at + 240]) is None


def test_the_refusal_says_what_a_human_should_look_at():
    """A refusal a reader cannot act on is a refusal they will override."""
    assert "declares itself" in REFUSAL
